### ISSUE TITLE
[Heroku Data] [Labs]: Enable Data Features such as WAL Compression

### ISSUE THREAD

**Issue by afawcett** [heroku/roadmap#102]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Heroku Data

### Tell us about what you're trying to solve. What challenges are you facing?

```markdown
This feature gives customer the ability to enable Beta features without having to call our support team. We will soon launch Heroku Data Labs CLI. With the ability to enable Postgres Advanced Certs and Postgres WAL Compression without having to contact support.
```

**Comment by jbrown-heroku** [comment]
[Heroku Data Labs](https://devcenter.heroku.com/articles/heroku-data-labs) features have been added:
- [Enhanced Certificates for Heroku Postgres](https://devcenter.heroku.com/articles/heroku-postgres-enhanced-certificates): This is useful if "real-cert" is required in your use-case, such as certain BI tools.
- [WAL Compression for Postgres Add-ons](https://devcenter.heroku.com/articles/heroku-data-labs-wal-compression): This may benefit if the database usage pattern contains many writes, however there are tradeoffs.
