### ISSUE TITLE
[Heroku][nonprofit]: Students and Nonprofit Program details

### ISSUE THREAD

**Issue by danieltalsky** [heroku/roadmap#109]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

heroku

### Tell us about what you're trying to solve. What challenges are you facing?

Back in August, Bob Wise made this blog post reminder about the end of the Heroku free tiers and announcing an upcoming `Students and Nonprofit Program` plan:
https://blog.heroku.com/next-chapter

I had hoped there would be some announcement about the Nonprofit Program before the Heroku free plan cutoff, but I haven't yet seen one and now the cutoff is at hand.

In the post, he invites people to contact him directly at his linkedin, and I sent him the following message, which was never answered:
 
> We're a non-profit arts organization and the removal of the free Heroku tier is going to sting!
Hi Bob,
> 
> Thanks for inviting people to contact you directly about the decision to end Heroku's free tier completely.  We're a non-profit arts organization called Satellite Collective (I'm the director of technology).
https://satellitecollective.org/
> 
> We created a small rails project for a web application that is also an art project and deployed it on Heroku's free tier: 
> http://telephone.satellitecollective.org/
> 
> Briefly we did pay for some commercial Heroku usage when we launched and had a NY Times article written about the project:
https://www.nytimes.com/2015/04/19/arts/design/telephone-an-international-arts-experiment-by-nathan-langston.html
> 
> Now we'd like to continue hosting the project for archival purposes, but can't really afford to pay for even the cheapest Heroku tier in perpetuity.  Also, it would take some significant development effort to adapt the application to another platform.
> 
> Is there some possible alternative Heroku can offer us as a non-profit arts organization?
>
> Daniel

Now I am getting reminder emails about the cutoff of free services but haven't had any news of your nonprofit program yet.  Can someone direct me to the details of the program or tell me who I can contact about it?

**Comment by dieskim** [comment]
We manage Heroku accounts for a couple of Non Profits as well. It would be great to get some update on this.

**Comment by danieltalsky** [comment]
Please like this post if you're frustrated with the lack of response to questions about Heroku's programs with the deadline rushing up:
https://www.linkedin.com/posts/danieltalsky_herokus-next-chapter-activity-6995942795395952640-YiFh?utm_source=share&utm_medium=member_desktop

**Comment by friism** [comment]
Thanks for opening this. We announced our participation in the GitHub Student Developer program here: https://blog.heroku.com/github-student-developer-program


If it's OK, I'm going to close this issue. There's related debate here:

* https://github.com/heroku/roadmap/issues/58
* https://github.com/heroku/roadmap/issues/18
