### ISSUE TITLE
Support for PostgreSQL 15

### ISSUE THREAD

**Issue by friism** [heroku/roadmap#110]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Postgres

### Tell us about what you're trying to solve. What challenges are you facing?

PG 15 was [released on October 22nd](https://www.postgresql.org/about/news/postgresql-15-released-2526/). Heroku Postgres usually only adds support for a new major version once the first point release (15.1 in this case) is out. This issue is for anyone wanting to track the release status.

PG 15 has new and exciting features that Heroku customers want.

**Comment by jbrown-heroku** [comment]
Postgres version 15 on Heroku is now in Beta: https://devcenter.heroku.com/changelog-items/2543
Please share your feedback

**Comment by jbrown-heroku** [comment]
Postgres 15 on Heroku is now released as GA and is the default version!
https://devcenter.heroku.com/changelog-items/2551
