### ISSUE TITLE
A new security plan with the legit bots in place 

### ISSUE THREAD

**Issue by 16CentAstrology** [heroku/roadmap#124]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

comfiting and GitHub programming 

### Tell us about what you're trying to solve. What challenges are you facing?

```markdown
the migration platforms are behind
```

**Comment by friism** [comment]
@16CentAstrology it's a little unclear to me what you're asking for here, can you provide more details?
