### ISSUE TITLE
Support ACM and manual SSL certs on Eco Dynos

### ISSUE THREAD

**Issue by coreyhaines** [heroku/roadmap#125]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Heroku dynos

### Tell us about what you're trying to solve. What challenges are you facing?

I would like to see ACM and manual SSL certs supported on eco dynos. Considering the security implications of non-ssl-secured sites, plus the ease of access using Let's Encrypt, not supporting SSL feels like it is opening up a new floodgate of insecure sites being built.

**Comment by friism** [comment]
Thanks for opening this issue. Note that manually obtained and uploaded certificates _do_ work with Eco apps, it's only Automated Certificate Management (ACM) that's not available (after posting this comment I'm going to tweak the issue description to reflect this).

Having said that, I think I agree that we should endeavor to make ACM available to Eco apps too

**Comment by friism** [comment]
Sorry, I made a mistake - manually uploaded certificates are _not_ supported with Eco apps. My previous comment still stands though: this is something we'd like to enable.

**Comment by KWW-BeeLine** [comment]
+1

I have spent decades doing development and support for low bandwidth NGO's around the world, and after learning today of this nonsense Heroku tax on poor people (no SSL cert for you unless you pay Heroku too much for services you don't need silly poor NGO, just get more money!) I will *STRONGLY* recommend against ever using Heroku to all my clients going forward and will be working with existing clients to remove them from Heroku ASAP.

There is NO REASON that a site shouldn't be able to use a free Let's Encrypt cert other than corporate greed.  SHAME ON YOU HEROKU.

If you are considering a Heroku deployment: DON'T DO IT: contact me direct and I'll point you to options that don't fleece poor people.

**Comment by ncomet** [comment]
> 

I agree that security should never be a trade-off... That's a big deal breaker for companies.

**Comment by ncomet** [comment]
> +1
> 
> I have spent decades doing development and support for low bandwidth NGO's around the world, and after learning today of this nonsense Heroku tax on poor people (no SSL cert for you unless you pay Heroku too much for services you don't need silly poor NGO, just get more money!) I will _STRONGLY_ recommend against ever using Heroku to all my clients going forward and will be working with existing clients to remove them from Heroku ASAP.
> 
> There is NO REASON that a site shouldn't be able to use a free Let's Encrypt cert other than corporate greed. SHAME ON YOU HEROKU.
> 
> If you are considering a Heroku deployment: DON'T DO IT: contact me direct and I'll point you to options that don't fleece poor people.

I agree that security should never be a trade-off. That's a major deal breaker for companies, hope it will change soon.

**Comment by andre5oto** [comment]
This is the type of feedback we like to see to help us set priorities for our project backlog. We will begin discussions with internal teams for assignment, planning and scheduling of this work.

**Comment by asaganda** [comment]
So for apps deployed on eco dynos, there isn't a method to get a secure connection via SSL cert?

**Comment by ncomet** [comment]
> So for apps deployed on eco dynos, there isn't a method to get a secure connection via SSL cert?

Precisely. Hard to believe right?

**Comment by asaganda** [comment]
After I left my comment, I came to realize that my other apps on Heroku's eco dyno have a secure connection and run as expected

**Comment by mryurii** [comment]
+1 it's a bummer 🙄

**Comment by andre5oto** [comment]
Quick update: the work to enable ACM and manual certs on Eco is coming along with an anticipated release in the coming weeks.

**Comment by vivekvj01** [comment]
Hi,

To provide an update, we are actively working on this feature Please stay tuned this month

**Comment by vivekvj01** [comment]
We have [released](https://blog.heroku.com/automatic-certificate-management-for-eco-dynos?preview=2c1272d8d76c4ba79aa96c92a8d5ad17) this today.

**Comment by ncomet** [comment]
> We have [released](https://blog.heroku.com/automatic-certificate-management-for-eco-dynos?preview=2c1272d8d76c4ba79aa96c92a8d5ad17) this today.

You rock 🤘 thanks a lot!

**Comment by xavdid** [comment]
The [pricing page](https://www.heroku.com/pricing) still implies that "Free SSL" is only available on basic dynos, not eco ones:

<img width="337" alt="image" src="https://github.com/user-attachments/assets/a3aea334-b802-47b9-bcb5-3abe80671c3f">

Is that just a matter of the docs being out of date?
