### ISSUE TITLE
Refresh of getting started guide content

### ISSUE THREAD

**Issue by capeterson** [heroku/roadmap#14]
Some of our language specific getting started guides have languished and need to be updated. While we have updated the guides to take into account changes in our pricing models, ie, the removal of free plans, we need to ensure that the guides do not contain spurious warnings or references to vastly outdated dependencies.

**Comment by so-rodriguez** [comment]
@capeterson Thank you for your patience with the delay in this response. We hear you on this. We've done a good bit of work since this comment in August and it might be a good idea to continue this conversation wit respect to the current docs. Looking forward to hearing back from you. Thanks!
