### ISSUE TITLE
Improve Ability to Contact Heroku and Heroku Support

### ISSUE THREAD

**Issue by JorDaneeKey** [heroku/roadmap#144]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### Tell us about what you're trying to solve. What challenges are you facing?

1. Publish clearly all means of contacting Heroku on [Heroku.com](http://heroku.com/)
2. Add a form for help if a user is locked out of their account or otherwise unable to open a support ticket
3. Review current flows and streamline the customer experience

**Comment by JorDaneeKey** [comment]
Updated https://www.heroku.com/contact and added https://www.heroku.com/account-lockout.

**Comment by andre5oto** [comment]
We updated the Heroku Support email auto-reply to include the [account-lockout URL](https://www.heroku.com/account-lockout). 

Two new KB articles were also published to help customers find their way to Heroku Support if they run into any problems creating their new Heroku account:
https://help.heroku.com/AK4EEL03/what-if-i-m-unable-to-log-into-heroku-com-to-contact-heroku-support
https://help.heroku.com/2BF1G5Q5/how-can-i-contact-heroku-support-if-i-m-unable-to-create-an-account-to-log-into-heroku-com

**Comment by Smi41** [comment]
Hi heroku assistance by the way I have a little problem some people use false card to have access to Heroku for bots I am going to koyeb and their security system is more so I would like you to pay attention to the false count so that everyone resumes their place.
