### ISSUE TITLE
Simplify alerting from Heroku Postgres metrics logs

### ISSUE THREAD

**Issue by mble-sfdc** [heroku/roadmap#184]
## Required Terms
- [x] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

## What service(s) is this request for?
Heroku Postgres, Heroku Redis, Apache Kafka on Heroku

## Tell us about what you're trying to solve. What challenges are you facing?

Currently, [Heroku Postgres metrics logs](https://devcenter.heroku.com/articles/heroku-postgres-metrics-logs) provide absolute values for figures like `db_size`, `read_iops` etc, but do not provide "caps", which are based on the [technical characterisation for a given plan](https://devcenter.heroku.com/articles/heroku-postgres-production-tier-technical-characterization).

To prevent customers from having to hard-code these limits into their monitoring, instead provide them in the metrics logs themselves/provide a % consumption of these limited resources for easier monitoring and alerting setups.

**Comment by ombr** [comment]
And it would be great to get automatic notification or if we could configure the notification (like heroku alerts)

**Comment by jbrown-heroku** [comment]
@mble-sfdc Thank you for logging this. 
We are looking into adding this to our metrics output. No target date yet, but we will review our prioritization to try to get this added.

**Comment by jbrown-heroku** [comment]
We've made improvements to our logs to show 0.0-1.0 scale for various metrics: https://devcenter.heroku.com/changelog-items/2977
