### ISSUE TITLE
Python 3.7 EOL, removal of its support in new builds on Heroku

### ISSUE THREAD

**Issue by ASayre** [heroku/roadmap#198]
Python 3.7 has gone [EOL](https://devguide.python.org/versions/).  In line with our [support policy](https://devcenter.heroku.com/articles/language-support-policy), we will soon be removing support for new builds targeting this version from the Heroku platform.  Existing applications will continue to run.

**Comment by edmorley** [comment]
https://devcenter.heroku.com/changelog-items/2719
