### ISSUE TITLE
Allow controlling PostgreSQL's `log_min_error_statement` setting

### ISSUE THREAD

**Issue by RealOrangeOne** [heroku/roadmap#200]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Heroku Postgres

### Tell us about what you're trying to solve. What challenges are you facing?

Under certain conditions, such as when queries error for unexpected reasons, Heroku Postgres will include the full query with the log. These queries may contain sensitive data (in some cases, PII), which it would be ideal to keep out of our log streams.

Because the query can spread into multiple log lines, it's not possible for to filter this as it's ingested into logs easily.

PostgreSQL claims this can be configured with the [`log_min_error_statement`](https://postgresqlco.nf/doc/en/param/log_min_error_statement/) setting, currently set to `ERROR`. Having the ability to increase this (to `PANIC`) should remove these queries from the logs, albeit at the cost of being unable to see query information when there are issues.

Raising here as recommended from support ticket.

**Comment by jbrown-heroku** [comment]
We are looking into providing configurability of `log_min_error_statement`. This might be small enough effort that we could deliver soon. As soon as we have clear plan, we will update.

Thank you for raising this @RealOrangeOne!

**Comment by jbrown-heroku** [comment]
We have made improvements to `pg:settings` for Heroku Postgres, which now includes adjustable `log-min-error-statement`: https://devcenter.heroku.com/changelog-items/2976

Thank you for tracking @RealOrangeOne !
