### ISSUE TITLE
PG Vector support for review apps

### ISSUE THREAD

**Issue by stof** [heroku/roadmap#239]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Postgres

### Tell us about what you're trying to solve. What challenges are you facing?

https://github.com/heroku/roadmap/issues/156 added support for `pg_vector` but only for non-Essential tier databases. As review apps are running using an Essential-tier database, it makes it impossible to use both `pg_vector` and review apps.

It would be great to bring `pg_vector` to Essential-tier databases as well.

**Comment by jefflub** [comment]
Adding a +1 here. We don't use review apps, but we have multiple staging and demo environments running on Essential-tier databases. Forcing us to upgrade these would add hundreds of dollars of monthly cost with no real benefit.

**Comment by GoffAC** [comment]
We are exactly the same as @jefflub 
It's really stunting our development - why was this restricted from Essential?

**Comment by lpradovera** [comment]
Same issue here, we use many staging/review apps that are breaking the bank at the moment.

**Comment by ElMantos** [comment]
+1

**Comment by clarence-inventive** [comment]
+1, this is breaking our use of review apps

**Comment by jbrown-heroku** [comment]
Thank you for your patience! We have an exciting update for review apps and Essential tier databases.
If you haven't done so already, please take a look at this changelog: https://devcenter.heroku.com/changelog-items/2862
We are migrating Essential Mini/Basic databases to the new Essential-0/1/2 databases with a planned GA date of May 8th 2024, which comes with pgvector. If you specified the specific database type in your code (i.e. app.json), please update to specify `essential-x` (0/1/2) instead.

At this time, Essential-0/1/2 are in public Beta until May 8th.
Here's more information around the new Essential-tier plans: https://devcenter.heroku.com/articles/postgres-essential-tier

**Comment by jbrown-heroku** [comment]
We launched Essential-0/1/2 plans with `pgvector`!
https://devcenter.heroku.com/changelog-items/2877
We have set Essential-0 as default for Review Apps/CI. Thank you for all your support!

**Comment by QuentinFarizon** [comment]
@jbrown-heroku Is it planned to add pgvector to in-dyno databases ?

**Comment by stereoscott** [comment]
> [@jbrown-heroku](https://github.com/jbrown-heroku) Is it planned to add pgvector to in-dyno databases ?

What did you end up doing to support CI on apps that use pgvector?
