### ISSUE TITLE
PostgreSQL 16(.1)

### ISSUE THREAD

**Issue by ur5us** [heroku/roadmap#242]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

PostgreSQL

### Tell us about what you're trying to solve. What challenges are you facing?

There are numerous features in a major release but for me personally performance and SQL/JSON query language features are usually quite high on the list for reasons to upgrade.

- https://devcenter.heroku.com/articles/heroku-postgres-version-support
- https://www.postgresql.org/about/news/postgresql-16-released-2715/
- https://www.postgresql.org/about/news/postgresql-161-155-1410-1313-1217-and-1122-released-2749/

**Comment by jbrown-heroku** [comment]
@ur5us Thank you for logging this. 
We are working on getting PG16 ready to ship. I will update with more info soon.

**Comment by andreas-venturini** [comment]
@jbrown-heroku will PostgreSQL 16 be GA by end of April?

**Comment by jbrown-heroku** [comment]
Thank you for waiting patiently.
We are targeting to GA in May. If we can deliver sooner, I will update.

**Comment by tomwilshere** [comment]
@jbrown-heroku Thanks for the updates? do you know when you're targeting beta release by? (or are you looking for alpha/beta testers!)

**Comment by jbrown-heroku** [comment]
Thank you for waiting!
We released PG16 Beta today: https://devcenter.heroku.com/changelog-items/2776
Please try it and let us know if you have any questions!

**Comment by jbrown-heroku** [comment]
We released PG16 today: https://devcenter.heroku.com/changelog-items/2777
Now available on all tiers of databases. 
Should you face any challenges, please log a support ticket. I'll be closing this item out.
Thank you all for your support!
