### ISSUE TITLE
Heroku-24 stack support (based on Ubuntu 24.04)

### ISSUE THREAD

**Issue by ASayre** [heroku/roadmap#255]
With the upcoming release of Ubuntu 24.04 LTS in April 2024, we will release the Heroku-24 stack to coincide with the upstream release.

See https://devcenter.heroku.com/articles/stack#stack-support-details for more information.  We will be following a similar pattern release pattern as we undertook with the[ Heroku-22](https://devcenter.heroku.com/articles/heroku-22-stack) stack.

**Comment by edmorley** [comment]
The Heroku-24 stack has now been released! 🎉 
https://devcenter.heroku.com/changelog-items/2898
https://devcenter.heroku.com/articles/heroku-24-stack

**Comment by jeffbax** [comment]
Appreciate the launch, but attempting to use it I'm running smack into the [memory changes](https://devcenter.heroku.com/articles/heroku-24-stack#changes-to-build-instances)

```!
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
ERROR: Build terminated: Out Of Memory
```

There is pretty limited documentation on this change or how to resolve this type of thing, just mention of `cgroups` that I don't see any which define what the build actually uses?

So it might go a long way for some docs to help:
1. Determine how much memory is available to the build (and build specs in general I guess)
2. Resources related to common problems and resolutions

Which for us, it seems like the webpack build is pushing node over the limit, as we had already set `--max_old_space_size=2560` under the previous `Heroku-22`.

TBD whether un-setting that helps get us around this or not (I am guessing no, and we'll be remaining on 22 until we have more time to dig into things)

**Comment by jeffbax** [comment]
> @jeffbax : We're making some improvements here soon to expand the available memory; stay tuned!
> 
> [#307 (comment)](https://github.com/heroku/roadmap/issues/307#issuecomment-2289295192)

Glad to hear... FWIW for certain app stages, we do use Github CI to build our assets en total and then push/pull those from S3 (not quite ideal to have to build out this custom pipeline, but we were doing it anyway to make sure they built) 

Yet there is no way to have review-apps wait for Github CI to pass (only Heroku CI it seems) before starting their build, so they can't pull whatever we generate and it will force a rails asset compilation -- which runs into the resource limitations pretty easily these days
