### ISSUE TITLE
Support for using passkeys to log in to Heroku (passwordless login)

### ISSUE THREAD

**Issue by friism** [heroku/roadmap#259]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Identity, Security

### Tell us about what you're trying to solve. What challenges are you facing?

Other [services support passwordless login](https://developers.google.com/identity/passkeys) with passkeys, we should consider whether that'd be appropriate for Heroku.

Salesforce (which Heroku relies on for MFA) already has some support for passkeys: https://ideas.salesforce.com/s/idea/a0B8W00000NHkSEUA1/add-passkey-support-for-logging-in

**Comment by andre5oto** [comment]
We will update on passkey development and support in https://github.com/heroku/roadmap/issues/298.
