### ISSUE TITLE
Support for poetry, the Python package manager

### ISSUE THREAD

**Issue by ASayre** [heroku/roadmap#269]
[poetry](https://python-poetry.org/) is a popular package manager for the Python ecosystem.  We should support this.

See https://github.com/heroku/heroku-buildpack-python/issues/796 for additional context.

**Comment by edmorley** [comment]
We've now added support for Poetry to the Python buildpack 🎉 
https://devcenter.heroku.com/changelog-items/3050

**Comment by edmorley** [comment]
We've now added support for Poetry to the Python buildpack 🎉 
https://devcenter.heroku.com/changelog-items/3050
