### ISSUE TITLE
Shutdown of final Postgres 9.6 databases

### ISSUE THREAD

**Issue by capeterson** [heroku/roadmap#27]
Heroku Postgres 9.6 has been end-of-life and customers making use of it have been subject to automatic upgrades where possible. However there are a few customers where automatic upgrades have failed. 

We've been in touch by email to urge a manual upgrade for these customers, and in the near future we will need to actually shut down database instances that are still running PG9.6

**Comment by jessehanley** [comment]
@capeterson some of the communication has been confusing here. Isn't PG 10 also being deprecated in November? 

Would be nice if there was a zero downtime upgrade whereby you could setup a follower in the new version then just promote it when the WAL is synced.

**Comment by ombr** [comment]
Postgresql upgrade are a pain point on heroku. It would be great to have a fully automated process or even better a zero downtime upgrade. (We don't want to spend time on every postgres release and every time we want to move to a bigger plan)

**Comment by capeterson** [comment]
@jessehanley yes, PG10 is being EOL'ed soon (https://devcenter.heroku.com/articles/heroku-postgresql#version-support). This card represents that there are a few customers with PG9.6 databases still running where automated upgrades have failed. We've been emailing DB owners about the urgent need to upgrade these very EOL'ed databases, but are approaching the point where we need to turn off the remaining ones if not upgraded. 

We've been trying to over-communicate this given the impact that turning off a DB instance can have. Anybody impacted should have received multiple emails about the issues by now as in addition.

We will at some point be forced to look at PG10 the same way, but that's a little further down the road.

@afawcett keep me honest here.

@ombr @jessehanley - I *think* https://github.com/heroku/roadmap/issues/38 is making the same request as you are here, can you take a look at thumbs up it if so? If I'm misreading the details and it's a distinct request I'd ask you to file a new issue to the request doesn't get lost when the final PG9.6 EOL/shutdown is complete.

**Comment by jbrown-heroku** [comment]
Postgres 9.6 has been completely deprecated from Heroku Postgres fleet.
We are committed to provide safer and better experience for our customers and this is among that effort.

I understand we have discussions around the upgrade pain in this thread, which we have noted. Thank you all for sharing your thoughts.
