### ISSUE TITLE
Heroku private space compatibility  issues with vpn gateway services

### ISSUE THREAD

**Issue by shiladityab24** [heroku/roadmap#275]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Heroku Private Space VPN 

### Tell us about what you're trying to solve. What challenges are you facing?

To connect to a Heroku Private Space, we typically use either VPC peering or an IPSec VPN. The Heroku documentation (https://devcenter.heroku.com/articles/private-space-vpn-connection) lists compatible VPN gateways, including AWS, GCP, Azure, and StrongSwan (an open-source option). Our client has a requirement that prevents us from using VPC peering or any of the listed VPN gateways.  We need to identify an alternative IPSec VPN solution, compatible with Heroku Private Spaces, that can be used on Windows machines.

**Comment by shiladityab24** [comment]
Can anyone provide some resolution to this issue. Reason for asking, we have already whitelisted the IP addresses used by our Azure Gateway, but in return, the access is blocked and IP resolved by gateways shows it as starting with 10…* network, since it resembles to be private network. Hence, we cannot access the dyno apps from the allowed IP ranges. What is the exact root cause of this issue.

**Comment by piyali-salesforce** [comment]
Hi @shiladityab24 , Thanks for reaching out. Have you tried to create a support ticket for this? The support team should be able to help you with this. Let me know if you still need help with this.

**Comment by shiladityab24** [comment]
Hello @piyali-salesforce  yes I have created a ticket on Heroku support **#1371302 - Dyno app access from allowed ip ranges not working** . Can you please look into this issue.

**Comment by andre5oto** [comment]
https://heroku.support/1371302 is resolved; closing this request.
