### ISSUE TITLE
Heroku Free Usage Reporting CLI Plugin

### ISSUE THREAD

**Issue by afawcett** [heroku/roadmap#28]
**Motivation**
Enable customers easily determine current Heroku free tier usage and take action.

**Details**
This will be a CLI plugin for the Heroku CLI, built on top of the Heroku Platform API's and shared as an open source project.

**Comment by hone** [comment]
This has been shipped here: https://github.com/heroku/heroku-cli-plugin-free/.

**Comment by Taptaplit** [comment]
Thanks, was really looking forward to this!!
