### ISSUE TITLE
Azure ad

### ISSUE THREAD

**Issue by Realtech1** [heroku/roadmap#299]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Salesforce functions 

### Tell us about what you're trying to solve. What challenges are you facing?

Not having this implemented will cause my automations to not succeed successfully

**Comment by jjsfdc** [comment]
This doesn't look like a Heroku product request, closing as out of scope.
