### ISSUE TITLE
ACM wildcard certificates

### ISSUE THREAD

**Issue by agrobbin** [heroku/roadmap#39]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Automated Certificate Management

### Tell us about what you're trying to solve. What challenges are you facing?

Let's Encrypt added support for [wildcard certificates](https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates) back in 2018 (according to [this post](https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578)).

It'd be great if Heroku's ACM also offered support for wildcard certificates!

**Comment by danaspiegel** [comment]
👍

**Comment by afawcett** [comment]
Thanks for this @danaspiegel - this seems like a pretty reasonable ask to me - will discuss with the team.

**Comment by andreas-venturini** [comment]
@afawcett has this issue since been removed from the [Roadmap](https://github.com/orgs/heroku/projects/130/views/1)?

We have two apps for which we'd like to enable ACM but currently cannot due to the limitation that apps using ACM are not allowed to have wildcard certs. Mostly happy with our Heroku enterprise plan but this the lack of ACM support for apps w/ wildcard certs is really annoying and adding unnecessary devops overhead for our team. 
Would be glad to provide more info or our use case for this.

**Comment by timharding** [comment]
@afawcett Hi Andrew, would like to +1 this. We've got 2 applications/4 environments that have wildcard domains and ACM would save us hundreds of pounds, a number of hours, and a reasonable amount of concern each year in dealing with certificates. Thanks.

**Comment by andreas-venturini** [comment]
Would be nice if Heroku provided an update re the status after ~1 year of research phase. It's hard to understand why this feature is still missing in 2024 given that this is a de facto standard on virtually all Heroku competitor platforms.

**Comment by egeek** [comment]
Any update here? It's really disappointing that neither this, nor HTTP/2 (#34) support is provided.

**Comment by timharding** [comment]
Another bump for this. Great to see it is being worked on. We're due for renewals in June 2025 and this would save us hundreds of pounds in certificate purchases. Otherwise we're wondering about putting AWS load balancers in front of Heroku so we can have them manage our wildcard certificates. 

Please get this sorted. It's the one issue we have with Heroku that makes us consider alternatives.

**Comment by elimchaysengSF** [comment]
Hey all - wanted to give a small update. We've been juggling this initiative between our Router 2.0 and HTTP/2 projects and the path to GA for that router and feature. That said, we've made really great progress for Wildcard ACM through June. We're closing in on a target launch date. Not quite finalized yet, but excited to get this in customer's hands as soon as we can!

**Comment by timharding** [comment]
@elimchaysengSF happy set this up on our two staging environments if it is helpful to have beta testing.

**Comment by kiejo** [comment]
It looks like this feature has been released: https://blog.heroku.com/heroku-acm-now-supports-wildcard-domains

**Comment by timharding** [comment]
@kiejo were you able to get this to work, just trying it now in staging and it tells me it doesn't like wildcards in both the web interface and the CLI.

**Comment by friism** [comment]
@timharding could you try again? It may be that we were still in the process of rolling out the change when you tried. Sorry about that.

**Comment by timharding** [comment]
@friism yep! That's working on one of our staging environments now. A few moments of downtime while it instantiated. This will save us a few hours of my time and few hundred bucks a year on manual certificates and, more importantly, automate a process that I could forget to manage. Thank you.

**Comment by kiejo** [comment]
> @kiejo were you able to get this to work

I've tested it earlier today and it worked as expected for me. Good to hear that's it's now working for you as well :)

**Comment by elimchaysengSF** [comment]
As mentioned above, we're excited to have delivered this for our Common Runtime customers. Stay tuned for Private Spaces support early next year as we roll out more changes specific to the Private Spaces product! 

See the Blog Post:
https://blog.heroku.com/heroku-acm-now-supports-wildcard-domains

 and Changelog: https://devcenter.heroku.com/changelog-items/2969
