### ISSUE TITLE
[service] [request]: Gig Worker App Type

### ISSUE THREAD

**Issue by ddfridley** [heroku/roadmap#41]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

dynos

### Tell us about what you're trying to solve. What challenges are you facing?

With the free dynos going away, it would be valuable to have paid dynos that would spin down when they have nothing to do, and stop the billing too. 

This is like a gig worker in the freelance space, you pay for them only when needed. 

I have a couple of free apps, where they spin up when they receive a web request (just like free dynos do) do their processing, and then exit.  Heroku currently restarts them and keeps these up for another hour, and then shuts them down.

A an example is an app/process the uses puppeteer to generate a snapshot of a new page on my main website, and then store that in Cloudinary, and store the URL in a database (Mongo Atlas these days) to be used as the social media preview image for the page on the next time it is accessed on the main server.

The process is compute intensive so I don't want to run it on the main server, and it is doesn't happen very often.  I would gladly pay a prorated rate, but need a way to make it automatic rather than manual. 

If it matters there are in node. 

A similar application would be QA test servers. I want to push code to a server to test, before pushing to production.  I don't want to have to remember to turn off the server when I'm done testing, I just want it to spin down until the next time I use it or push code to it.  Again -happy to pay for the compute cycles I use but want a way for the billing to stop automatically.

I see that you have this: https://devcenter.heroku.com/articles/background-jobs-queueing#implementation but I have never tried it, nor needed to because the free dyno's solved my problem.  But development wise, these processes are independent apps, with their own repos. It's been really easy to do it this way.

**Comment by friism** [comment]
Hey, after you opened this issue we did announce the addition of low-cost idling Eco-dynos. I hope that helps: https://blog.heroku.com/new-low-cost-plans
