### ISSUE TITLE
[Dynos & Data] [request]: Re-introducing free services for GitHub Educational Pack

### ISSUE THREAD

**Issue by pasindujr** [heroku/roadmap#45]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Dynos

### Tell us about what you're trying to solve. What challenges are you facing?

```markdown
As the upcoming changes will remove Heroku's free services and Salesforce have mentioned about their commitment to education, re-introducing free dynos to GitHub Educational Pack would be useful for students who work on their developer journey.
```

**Comment by capeterson** [comment]
We promised answers for students - and we're working on it! Adding this to the roadmap's researching column until we have more details to share. @JorDaneeKey heads up

**Comment by pasindujr** [comment]
@capeterson Thank you!

**Comment by capeterson** [comment]
We've officially announced out partnership with the GitHub educational pack program that includes Heroku credits for students. Take a look at https://www.heroku.com/github-students for more info on the offer.

I'm going to close this out, but please feel free to open new issues that reference this if you have further feedback/requests in this area!

**Comment by kanhaiya-2000** [comment]
I think there should not be any compilation of adding credit card details for students. And if asking details are compulsory,then there should be an option to add a debit card too(instead of credit card which may not be available to all students).

**Comment by kanhaiya-2000** [comment]
I think there should not be any compulsion of adding credit card details for students. And if asking details are compulsory,then there should be an option to add a debit card too(in addition to credit card,like AWS does) since many of us may not necessarily have a credit card.
