### ISSUE TITLE
[Dynos & Data] [request]: Free tier for staging apps in a pipeline

### ISSUE THREAD

**Issue by kouroubel** [heroku/roadmap#54]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

dynos, Postgres, Redis

### Tell us about what you're trying to solve. What challenges are you facing?

There should be a free (or reduced cost) tier for staging apps as long there is at least one paid production app in a pipeline.

Staging apps are only occasionally up, have minimum db requirements and generate no profit so it would not be fair to cost the same as production apps.

Completely eliminating the free tier would effectively double the cost of small projects to the point they become non-viable.

Alternatively, there could be a charge of some amount (e.g., $10/month) for the current free tier functionality.

**Comment by afawcett** [comment]
Thanks @kouroubel for your suggestion. Review apps are a powerful feature and we find customers can have an extended period of having them in review - also some apps for testing purposes some customers may require more resources. We would want to cover some cost in respect to this these. What are your thoughts on these situations and what level of resource, including compute and data did you have in mind? Meanwhile please review our latest Eco and Mini pricing plan announcement here https://blog.heroku.com/new-low-cost-plans

**Comment by kouroubel** [comment]
Thank you for the reply @afawcett. In my case, the eco plan and mini PG should be sufficient for both staging and/or customer testing. I am so glad about the eco dynos that sleep. I still have a concern with the mini PG (at $5/month) since sometimes I may not access a staging app for months. See my reply in #55.

**Comment by friism** [comment]
@kouroubel thanks for opening this - since your residual concerns (and they're valid to be clear) are about postgres, I'm going to close this issue in favor of this newly opened one: https://github.com/heroku/roadmap/issues/132
