### ISSUE TITLE
New low-cost options for Dyno & Data to cover small-scale use cases.

### ISSUE THREAD

**Issue by capeterson** [heroku/roadmap#55]
We've heard quite a bit of feedback about the need for low-cost options for active development use, lightweight review apps, and other similar use cases that don't require a fully "production" level app but want [dev/prod parity](https://12factor.net/dev-prod-parity). We're taking a look at what we can do to make this kind of lightweight use case that was previously well serviced by the free tier into something we carry forward as a lower cost than other options.

**Comment by capeterson** [comment]
Hoping to have a material update here in the next week or two, stay tuned.

**Comment by afawcett** [comment]
At Dreamforce this week present this update - more news coming soon!

![Image](https://user-images.githubusercontent.com/1167760/192001045-3d752b55-e844-4d8b-9fdf-8c20a269d28b.png)

**Comment by capeterson** [comment]
We just posted to the heroku blog with details on the changes: https://blog.heroku.com/new-low-cost-plans. Thanks to everybody who shared feedback however you sent it.

**Comment by kouroubel** [comment]
Sometime ago I opened an issue about keeping the free tiers for staging apps in a pipeline which, in general, are not accessed frequently (see #54). I feel that the new low-cost plans announced is a very good step that corrects (some of) the unfairness. Specifically,

- The new eco dynos are perfect. Dynos that are sleeping, fully address the issue of not being charged for something that I don't use.
- The new mini PG (at $5/month) is a partial improvement. Sometimes a staging app may not be accessed for months (or years?).

In order to not be charged for something that is "just sitting there", I am currently considering of making a backup of the staging app database, detaching it when I am not going to use it for a long time and then attaching it again and restoring the backup when work needs to be done. 

How about offering the possibility to "park and unpark" a database from the Heroku platform or CLI?

**Comment by ombr** [comment]
@capeterson let me add two points:

1/ As an enterprise customer I do not want to have to update all my review apps to hobby if I have one of them that is incidentally running for too long (it happened to us in the past with some webhooks notification) I would rather have an option on the review apps to limit their running time or an way to add some more hours for fixed pricing (a quick way to unblock the situation)

2/ We sometimes have review apps that are staying open for some time. I know there is the auto-destroy but it would be great if we could have a eco PG that would basically shutdown the database when the dyno is shutting down. (I would rather have it automated than to have to do it from the command line)

3/ Currently we do not have access to the hobby tier as an entreprise customer, will we get access to hobby and eco dynos ?

This is also valid feedback for #49 @afawcett

**Comment by desnw** [comment]
What about including 1 or couple of free ECO PostgreSQL DB's with the $5 ECO DYNO?  I think the $5 ECO Dyno is a pretty awesome idea to have it spread over all of your "ECO" apps and have it sleep.  This is really perfect for the DYNO part of the APP Picture.  
The DB Part is still a little pricy for people who just occasionally have the need.  If you can't include any free DBs with the $5 PAID Eco Dyno then what about offering SQLite for free with the ECO DYNO or offer it for something really cheap like a $1 or $2 per instance.  Keep your PostgreSQL for the apps that REALLY need it.  Hobby or testing apps probably don't need PostgreSQL.  I have a Hobby FoodLogger app that only myself and my GF really use and it would be fine with SQLite.  I don't know if there is another reason why you don't allow SQLite (Technical reason IE some kind of incompatibility with the Platform or?)

**Comment by lukasz-eond** [comment]
Hello @capeterson , thank you for leading this important change in Heroku plans!
The end of November is closer and closer and so is the end of the Free Tier. 
When should we expect the Eco plans to be available? It would be great to have 1-2 weeks to migrate.
Thanks in advance!
Lukasz Czerwinski
CTO of EonD

**Comment by irphilli** [comment]
> Hello @capeterson , thank you for leading this important change in Heroku plans! The end of November is closer and closer and so is the end of the Free Tier. When should we expect the Eco plans to be available? It would be great to have 1-2 weeks to migrate. Thanks in advance! Lukasz Czerwinski CTO of EonD

Piggybacking on this. Looks like the "mini" addons are available to Postgres and Redis. However, specifying something like `heroku-postgresql:mini` or `heroku-redis:mini` for the plan in app.json for review apps is still provisioning a Hobby instance. Would be nice if that would start provisioning mini instances as well so we can start moving ahead of time.

**Comment by capeterson** [comment]
@irphilli there's a few behind the scenes issues with how the pipelines consent process is interacting here, sadly I don't think we'll be able to fix this before the Nov 28th end of hobby plans. We have a test case for this now though, so thank you for flagging, and apologies we can't make the migration easier in the interim.

**Comment by dentarg** [comment]
@capeterson from https://devcenter.heroku.com/articles/ruby-database-provisioning

> By default, the lowest-cost [Heroku Postgres plan](https://devcenter.heroku.com/articles/heroku-postgres-plans#plan-tiers) will be added to any Ruby app that has the `pg` gem dependency, when deployed for the first time.

How will this behave after Nov 28th? Can I disable it? (I really don't need it.)

**Comment by friism** [comment]
@dentarg sorry about the slow response. Yes, you can make Heroku skip auto-provisioning the database by setting the `HEROKU_SKIP_DATABASE_PROVISION=1` config var. [Details on Dev Center](https://devcenter.heroku.com/articles/ruby-database-provisioning#skip-auto-provisioning-a-database).

**Comment by dentarg** [comment]
@friism Thanks for following up! I'm aware and using that, I created the ticket @schneems resolved with https://github.com/heroku/heroku-buildpack-ruby/pull/1349 :-)
