### ISSUE TITLE
Heroku Private data stores secure connection to Salesforce Functions

### ISSUE THREAD

**Issue by vivekvj01** [heroku/roadmap#59]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### Tell us about what you're trying to solve. What challenges are you facing?

Heroku data in functions https://developer.salesforce.com/blogs/2022/03/heroku-data-in-salesforce-functions

Currently works only for data stores running in the Common Runtime, for example Standard and Premium Postgres plans. It would be great to allow existing private data stores to be securely exposed to Functions.

**Comment by friism** [comment]
I think we have a solution for this now, closing: https://help.salesforce.com/s/articleView?id=000394313&type=1
