### ISSUE TITLE
New Postgres plans with emphasis on disk size flexibility

### ISSUE THREAD

**Issue by jbrown-heroku** [heroku/roadmap#60]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Postgres

### Tell us about what you're trying to solve. What challenges are you facing?

As an enterprise-ready PaaS, Heroku Postgres service is an important part of the solution. We have received feedback that larger Postgres plans do not scale well with customers’ business and they desire more flexible disk size options, including larger than 4TB that we currently offer with tier-9 Postgres instances.

The idea is to consider additional data products that are built on the same underlying infrastructure as current Postgres offerings, but with emphasis on addressing disk size at higher-tier databases, for example 6TB with tier-9 CPU/RAM. This should be a short/medium term solution with faster time-to-market while we invest in exploring longer term solution. We understand that this flexibility can provide immediate benefit to scale better on our platform.

**Comment by jknipp** [comment]
As a customer of Heroku, I can confirm that this is indeed an issue for us at Spreedly. We have been forced to upgrade to more expensive Postgres tiers simply to satisfy our disk space requirements.

**Comment by darkthirst** [comment]
Hi, 

Any expected timelines we have for this?
Our team at Mindbody also uses Postgres and this will be really helpful.

**Comment by jessehanley** [comment]
Hey what's the ETA on this? Renewing contract soon and whether we stay on platform depends on this ticket.

**Comment by jbrown-heroku** [comment]
We are actively working on this! I can't provide the ETA yet, but aiming for an expedited release.
Thank you for all the interest.

**Comment by darkthirst** [comment]
Hi Team,

Any updates on this one?

**Comment by jknipp** [comment]
I'm still hopeful this feature is released, as we would take advantage of it in some regard. However, due to the lack of progress on this roadmap item, we made the decision as part of our technical strategy to migrate away from Heroku for one of our larger and more expensive Postgres databases (`standard-9` plan) to use AWS RDS directly.

**Comment by jbrown-heroku** [comment]
We are working on new plans to accommodate larger disk usages. We are now including -6 and -9.  For resiliency reasons, they will be available on HA databases (Premium, Private, Shield plans).

**Comment by jessehanley** [comment]
Why wasn't this extended to Standard?
