### ISSUE TITLE
Larger Dyno Sizes (Private XL/Performance XL/GPU)

### ISSUE THREAD

**Issue by elimchaysengSF** [heroku/roadmap#66]
Evaluation of using larger and new AWS resources to provide larger dyno sizes for Heroku Online and Heroku Private Spaces Customers. Opportunity to reconsider [current sizing options](https://devcenter.heroku.com/articles/dyno-type) and will correspond to an overall dyno pricing and sizing optimization exercise in 2023. Additional details, can be referenced in the [Accelerated Computing EC2 Instance list](https://aws.amazon.com/ec2/instance-types/).

**Comment by elimchaysengSF** [comment]
If any customers have anecdotes about what limitations they currently face with our current dyno sizes, i.e. compute or memory based frustrations, please comment here!

**Comment by xqliu** [comment]
Jump from 1GB shared to 2.5GB dedicate directly without options like 1.5G, 2G makes deployment of JVM based application not convenient and suitable at all, User have to either to use 1GB shared one, which is not enough, or jump to use the 2.5G dedicate plan, which is too expensive.

Wish you can consider to add more planes which is suitable for JVM based application, 2GB would be a sweet spot for JVM scenario.

Thanks.

**Comment by ArturT** [comment]
@xqliu I agree, the jump from 1GB to 2.5GB is expensive.

For instance, we use background worker with Sidekiq Ruby gem. It would be good to have more memory, but no need for a fast CPU. A dyno type 3X with 3GB RAM and a shared CPU would be helpful.

**Comment by bradleybuda** [comment]
I made roughly the same proposal in #62 , perhaps these two should be unified?

**Comment by friism** [comment]
Closing this issue in favor of @bradleybuda's here https://github.com/heroku/roadmap/issues/62 Also see https://github.com/heroku/roadmap/issues/130
