### ISSUE TITLE
[service] [request]: describe request here

### ISSUE THREAD

**Issue by bobabarbanel** [heroku/roadmap#67]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

NonProfit, Public Service

### Tell us about what you're trying to solve. What challenges are you facing?

We have a dyno that runs during free public vaccination sessions. We need to continue us to be able to use this site for tracking vaccine usage and avoiding waste so we can continue use to deliver free vaccinations to all comers.

Please quickly let us know the details of how this will work going forward.

**Comment by afawcett** [comment]
@bobabarbanel per our [FAQ](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq) we are working on our non-profit program for next year. If you need to discuss further I would be happy to do so. Please raise a support case and request that the case has my attention thanks.

**Comment by bobabarbanel** [comment]
How do I do that?  Why is it necessary?You already know we need to discuss this ASAP. Bob Abarbanel+1 206-499-1443On Nov 15, 2022, at 19:37, Andrew Fawcett ***@***.***> wrote:﻿
@bobabarbanel per our FAQ we are working on our non-profit program for next year. If you need to discuss further I would be happy to do so. Please raise a support case and request that the case has my attention thanks.

**Comment by friism** [comment]
Hey there, if this is still relevant you can open a support ticket here: https://help.heroku.com/

I'm going to close this issue - efforts related to non-profits are tracked here: https://github.com/heroku/roadmap/issues/18

**Comment by bobabarbanel** [comment]
Thank you. We are happily using Heroku. Bob Abarbanel+1 206.499.1443On Jan 27, 2023, at 13:04, Michael Friis ***@***.***> wrote:﻿
Hey there, if this is still relevant you can open a support ticket here: https://help.heroku.com/
I'm going to close this issue - efforts related to non-profits are tracked here: #18
