### ISSUE TITLE
[service] [request]: Heroku program for non-profits?

### ISSUE THREAD

**Issue by martingluckman** [heroku/roadmap#72]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

In lieu of closing of free dynos would it be possible to create a program for registered non-profits?

### Tell us about what you're trying to solve. What challenges are you facing?

We are a small research institute based in India and have loved and grown since 2013 with Heroku, using the paid services when need be but very much benefiting for our research from the free services when we needed very small, occasionally used projects or to demo or proof something (as it was intended to be used).

It would be incredible of Heroku could continue to offer some free dynos for non-profits. All the other large players like Google are offering something for non-profits and I know there are beneficial balance sheet advantages assuming the non profit has an EIN and all its paperwork in order.

We also know Salesforce currently offers a brilliant non-profit offering https://www.salesforce.org/nonprofit/ which we are currently using for our fundraising so it is very much in alignment with Salesforce's broader ethos with non-profits.

Please could this be considered, I know there are many small research institutes and non-profits that would benefit immensely. Partnering with Techsoup or a similar body for vetting of genuine non-profits to avoid abuse would protect the program from abuse, alternately non-profits already part of the Salesforce non-profit program could automatically have access to the Heroku for non-profits offerings.

**Comment by afawcett** [comment]
Thank you @martingluckman for raising this. We are aware that our non-profit community is keen for an update. We are committed to this and are working on the design of this service internally. As soon as we have some update we will share. Thank you for your patience meanwhile.

**Comment by friism** [comment]
Thanks for opening this - we're tracking efforts to improve access to Heroku to non-profits on this issue: https://github.com/heroku/roadmap/issues/18

I'm going to go ahead and close this one.
