### ISSUE TITLE
[Dyno] [request]: Dyno other than free one can also be auto sleep

### ISSUE THREAD

**Issue by xqliu** [heroku/roadmap#73]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

dynos

### Tell us about what you're trying to solve. What challenges are you facing?

```markdown
Would like dyno other than free one can also be auto sleep

Some scenario is some JVM based application have to use more than 512MB memory, so standard-2x dyno is used, but actually they are used as a staging/dev environment, and would like it also be able to auto sleep like after 30 minutes.

This is quite important for many developer and small team's workflow.
```

**Comment by xqliu** [comment]
> You can do this with the auto idle plugin.

The single plugin cost 12.5 usd each month 😅

**Comment by kouroubel** [comment]
Standard is 10$/month and it _will_ save you money especially if you use it with a staging app.

**Comment by friism** [comment]
@xqliu thanks, this is a good idea. I think we can track it as part of https://github.com/heroku/roadmap/issues/111#issuecomment-1372689511 so I'll close this issue
