### ISSUE TITLE
[Functions] HIPAA Compliance

### ISSUE THREAD

**Issue by vivekvj01** [heroku/roadmap#76]
When you build and operate a mission critical application on Functions, you are entrusting Salesforce with critical and sensitive data about your business and about your customers. Nothing is more important to us than protecting the privacy of your data and that is why Trust is our number one value.

**Comment by andre5oto** [comment]
For many of our customers, processing health related data in Functions is critical to your business. We are happy to report that we are currently performing a 3rd party assessment of our HIPAA documentation and related controls. Once this assessment is completed and reviewed by relevant parties within Salesforce, we will be very close to adding Functions for HIPAA (written into our BAA). When that happens, we will update the status here again.

**Comment by andre5oto** [comment]
Salesforce Functions has been added to the Salesforce HIPAA Business Associate Addendum ("BAA") to process health-related data.
