### ISSUE TITLE
[Functions] Regions

### ISSUE THREAD

**Issue by vivekvj01** [heroku/roadmap#80]
In order to improve performance, reduce latency, and support data sovereignty requirements, Heroku will be adding in-region support for the data centers below. Currently, the list of available regions can be found in [this Private Spaces dev center article](https://devcenter.heroku.com/articles/private-spaces#regions). After this change, we are excited to offer the Salesforce Functions product in the five additional regions italicized below. 

| name      | location                |
|-----------|-------------------------|
| dublin    | Dublin, Ireland         |
| frankfurt | Frankfurt, Germany      |
| oregon    | Oregon, United States   |
| sydney    | Sydney, Australia       |
| tokyo     | Tokyo, Japan            |
| virginia  | Virginia, United States |

**Comment by vivekvj01** [comment]
We have made a subset of regions available 
https://developer.salesforce.com/blogs/2023/01/salesforce-functions-is-globally-available

**Comment by neoloans** [comment]
Is there any plan for data center in India?

**Comment by vivekvj01** [comment]
Hi @neoloans  yes we are actively working towards it.
