### ISSUE TITLE
[Functions] Private data stores in functions

### ISSUE THREAD

**Issue by vivekvj01** [heroku/roadmap#95]
Would like to connect securely to private data stores from functions. Currently we can use a Beta feature however we would like it be to be simpler.

**Comment by vivekvj01** [comment]
you can connect to a private space DB using this feature https://devcenter.heroku.com/articles/private-spaces#trusted-ip-ranges-for-data-services of allowlisting your function space stable outbound IP. If could you raise a case our support team should be able to provide you your stable outboundips for your space. We are working to make the ips more easily accessible aswell. Once you have completed the step of allowlisting the ip's. You can find sample code on connecting to the database can be found
 [here](https://github.com/trailheadapps/functions-recipes) sample code can be found here under Section No 6 Heroku Data
Heroku Data
[PostgreSQL (Node.js)](https://github.com/trailheadapps/functions-recipes/blob/main/functions/06_Data_Postgres_JS)
[PostgreSQL (Java)](https://github.com/trailheadapps/functions-recipes/blob/main/functions/06_Data_Postgres_Java)
[Redis (Node.js)](https://github.com/trailheadapps/functions-recipes/blob/main/functions/06_Data_Redis_JS)
[Redis (Java)](https://github.com/trailheadapps/functions-recipes/blob/main/functions/06_Data_Redis_Java)

**Comment by friism** [comment]
I think we have this documented now, closing: https://help.salesforce.com/s/articleView?id=000394313&type=1
