### ISSUE TITLE
New Regions for Private Spaces

### ISSUE THREAD

**Issue by elimchaysengSF** [heroku/roadmap#98]
In order to improve performance, reduce latency, and support data sovereignty requirements, Heroku will be adding in-region support for the data centers below. Currently, the list of available regions can be found in [this Private Spaces dev center article](https://devcenter.heroku.com/articles/private-spaces#regions). After this change, we are excited to offer the Private Spaces product in the ~~five~~ four additional regions italicized below. 

| name      | location                |
|-----------|-------------------------|
| dublin    | Dublin, Ireland         |
| frankfurt | Frankfurt, Germany      |
| oregon    | Oregon, United States   |
| sydney    | Sydney, Australia       |
| tokyo     | Tokyo, Japan            |
| virginia  | Virginia, United States |
| _singapore_ | _Singapore_               |
| _mumbai_    | _Mumbai, India_           |
| _montreal_  | _Montreal, Canada_        |
|~~_paris_~~    | ~~_Paris, France_~~  moved to FY25**       |
| _london_    | _London, UK_              |

As of May 3 2023, Mumbai and Montreal were released prior to full general availability of all 4 regions in a limited GA release and more details specific to the limited release can be found in this [roadmap item](https://github.com/heroku/roadmap/issues/175) and the [Heroku blog.](https://blog.heroku.com/private-spaces-expand-to-mumbai-and-montreal)

**Once this roadmap item is shipped, it will indicate that all four regions (Mumbai, Montreal, Singapore, and London) are released for general availability.**

**Comment by james-freec** [comment]
how about public for singapore?

**Comment by raphjutras** [comment]
Do you plan of offering some more regions for **Public** ?

As a startup, we are unable to afford enterprise plans and will be compelled to move our infrastructure to a different provider because our clients require that their data be hosted in Canada due to laws. We absolutely LOVE Heroku for its simplicity and it will be a hassle to switch to another provider. However, we have no other option but to do so :(

Canada (Montreal) region will be vital to our company in the next year.

Do you plan on taking care of your smaller customers in a near future?

**Comment by friism** [comment]
@raphjutras that's a great callout, could you open another issue? Also happy to do it for you

**Comment by raphjutras** [comment]
@friism I have opened an Issue for that.
[](https://github.com/heroku/roadmap/issues/166)
Thanks for the suggestion!

**Comment by elimchaysengSF** [comment]
** Heroku Paris regions have to be postponed to after 2023 due to the availability of AWS volume types in the Paris region and the table above has been updated accordingly.

**Comment by rushib1** [comment]
Any updates on the Mumbai region?

**Comment by elimchaysengSF** [comment]
We're excited to release two new regions (Mumbai and Montreal) as part of this effort: all the details are [on the Heroku Blog now!]( https://blog.heroku.com/private-spaces-expand-to-mumbai-and-montreal)

We're planning to go full general availability with these two regions later this year alongside London and Singapore, so please stay tuned for more formal updates and announcements about that following the limited release 👍

**Comment by raphjutras** [comment]
@elimchaysengSF Things are going forward! Can't wait to have Montreal in **Public / Common Runtime** :grin: :eyes:
Thank you.

**Comment by caiocclopes** [comment]
How about Sao Paulo? 🙏

**Comment by elimchaysengSF** [comment]
🚀 🌐 Our four new regions: Mumbai, Montreal, Singapore, and London are now GA'ed and live now! See the blog for even more details: https://blog.heroku.com/heroku-private-spaces-global-expansion
